

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Map port 3000 on the host to port 80 in the container
    networks:
      - my-app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Map port 5000 on the host to port 5000 in the container
    networks:
      - my-app-network
    environment:
      - NODE_ENV=production
      - PORT=5000

networks:
  my-app-network:
    driver: bridge
