name: Run Backend Jest Tests

on:
  push:
    branches:
      - main # Trigger on push to the main branch (or adjust to your default branch)
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch (or adjust to your default branch)

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root_password # Set MySQL root password (adjust as needed)
          MYSQL_DATABASE: test_db # Database to use for testing
        ports:
          - 3306:3306 # Expose port 3306 for the connection
        options: --health-cmd="mysqladmin ping --silent" --health-timeout=5s --health-start-period=10s --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Jest tests for the backend
        working-directory: ./backend
        env:
          MYSQL_HOST: 127.0.0.1 # MySQL host
          MYSQL_PORT: 3306 # MySQL port
          MYSQL_USER: root # MySQL user
          MYSQL_PASSWORD: root_password # MySQL password
          MYSQL_DATABASE: test_db # MySQL database
        run: npx jest # Run Jest tests
