name: Run Backend Jest Tests

on:
  push:
    branches:
      - main # Trigger on push to the main branch (or adjust to your default branch)
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch (or adjust to your default branch)

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Choose the Node.js version that suits your project

      - name: Install backend dependencies
        working-directory: ./backend # Change the working directory to the backend folder
        run: npm install

      - name: Set executable permissions for Jest binary
        run: chmod +x ./backend/node_modules/.bin/jest # Ensure Jest has executable permissions

      - name: Run Jest tests for the backend
        working-directory: ./backend # Run tests in the backend directory
        run: npx jest # Use npx to run Jest
